apiVersion: v1
kind: ConfigMap
metadata:
  name: pictureoftheday-config
  namespace: pictureoftheday
data:
  DEBUG: "False"
  DB_ENGINE: "django.db.backends.postgresql"
  DB_NAME: "pictureoftheday"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  TIME_ZONE: "UTC"
  USE_TZ: "True"
  ALLOWED_HOSTS: "picture.learntosolveit.com,localhost,127.0.0.1"
  CSRF_TRUSTED_ORIGINS: "https://picture.learntosolveit.com,http://localhost:8000,http://127.0.0.1:8000"
  STATIC_URL: "/static/"
  MEDIA_URL: "/media/"


