apiVersion: batch/v1
kind: CronJob
metadata:
  name: fetch-pictures-daily
  namespace: pictureoftheday
spec:
  schedule: "0 2 * * *"  # Run at 2 AM UTC daily
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: fetch
            image: registry.digitalocean.com/orsenthil/pictureoftheday:latest
            command:
            - sh
            - -c
            - |
              python manage.py fetch_picture --source apod
              python manage.py fetch_picture --source wikipedia
              python manage.py fetch_picture --source bing --fetch-all
            env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: pictureoftheday-secrets
                  key: SECRET_KEY
            - name: DB_ENGINE
              valueFrom:
                configMapKeyRef:
                  name: pictureoftheday-config
                  key: DB_ENGINE
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: pictureoftheday-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pictureoftheday-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pictureoftheday-secrets
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: pictureoftheday-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: pictureoftheday-config
                  key: DB_PORT
            - name: NASA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: pictureoftheday-secrets
                  key: NASA_API_KEY
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: pictureoftheday-secrets
                  key: OPENAI_API_KEY
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: pictureoftheday-config
                  key: ALLOWED_HOSTS
          restartPolicy: OnFailure


