apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pictureoftheday-ingress
  namespace: pictureoftheday
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - picture.learntosolveit.com
    secretName: pictureoftheday-tls
  rules:
  - host: picture.learntosolveit.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pictureoftheday-service
            port:
              number: 80


