apiVersion: v1
kind: Service
metadata:
  name: pictureoftheday-service
  namespace: pictureoftheday
spec:
  selector:
    app: pictureoftheday
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP


